export * from './patient-list/patient-list.component';
export * from './patient-registration/patient-registration.component';
export * from './patient-medical-history/patient-medical-history.component';
export * from './patient-visit-history/patient-visit-history.component';
export * from './shared/patient.service';
export * from './shared/patient.model';
export * from './shared/medical-history.model';
export * from './shared/visit-history.model';
export * from './patients-routing';
